ARGS:
 tab: 'pw3d_test'
 eval_dataset: 'pw3d_test'
 GPUS: 0
 model_version: 1
 
 val_batch_size: 16
 nw_eval: 2
 eval: True
 collision_aware_centermap: False
 collision_factor: 0.2
 calc_PVE_error: False

 backbone: 'hrnet'
 centermap_size: 64
 centermap_conf_thresh: 0.2
 model_precision: 'fp32'
 smpl_mesh_root_align: False

 model_path: /home/zx/human_pose_estimation/checkpoints/hrnet_cm64_V1_hrnet_on_gpu0,1_val/88_95.0093_56.0955_hrnet_cm64_V1_hrnet.pth
 dataset_rootdir: '/home/extend_data/data/pose_datasets/romp_datasets' #'/path/to/dataset/3DPW'